# Begin Project
project:
  type: website
  pre-render: wget -nc https://raw.githubusercontent.com/lmu-osc/branding-resources/refs/heads/main/lmu-osc-custom.scss
  post-render: rm lmu-osc-custom.scss
# End Project


# Begin Website
website:
  title: "TUTORIAL TITLE HERE"
  page-footer: 
    center: "Copyright, 2024 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/REPO-NAME-HERE
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  favicon: assets/LMU_OSC_favicon.jpg
  margin-header: |
    ![](/assets/LMU_OSC_logo.svg){width="175"}
  
  
  navbar:
    right: 
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/lmu-osc/REPO-NAME-HERE
          - text: Report a Bug
            url:  https://github.com/lmu-osc/REPO-NAME-HERE/issues
      - icon: house-heart
        url: https://www.osc.uni-muenchen.de/index.html
   
        
  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "FOUNDATIONS"
        contents:
          - href: 1_FOUNDATIONS_DATA_PRIVACY/1_1_Introduction_data_privacy.qmd
            text: "FOUNDATIONS Introduction"
          - href: 1_FOUNDATIONS_DATA_PRIVACY/1_2_Legal_Framework.qmd
            text: "FOUNDATIONS Legal Framework"
          - href: 1_FOUNDATIONS_DATA_PRIVACY/1_3_Key_concepts.qmd
            text: "FOUNDATIONS Key Concepts and Principles"
      - section: "FOUNDATIONS: DATA ANONYMISATION"
        contents:
          - href: 2_DATA-ANONYMISATION/2_1_Introduction.qmd
            text: "DATA-ANONYMISATION Introduction"
          - href: 2_DATA-ANONYMISATION/2_2_Key_concepts.qmd
            text: "DATA-ANONYMISATION Key Concepts"
      - section: "PROTECTION"
        contents:
          - href: 3_PROTECTION/3_1_Data_security_fundamentals.qmd
            text: "PROTECTION Data Security Fundamentals"
          - href: 3_PROTECTION/3_2_Individual_rights.qmd
            text: "PROTECTION Individual rights"
          - href: 3_PROTECTION/3_3_Risk_management.qmd
            text: "PROTECTION Risk management"
      - section: "ANONYMISATION TECHNIQUES"
        contents:
          - href: 4_ANONYMISATION_TECHNIQUES/4_1_Basic_methods.qmd
            text: "ANONYMISATION Basic methods"
          - href: 4_ANONYMISATION_TECHNIQUES/4_2_Advanced_techniques.qmd
            text: "ANONYMISATION Advanced techniques"
          - href: 4_ANONYMISATION_TECHNIQUES/4_3_Specialised_approaches.qmd
            text: "ANONYMISATION Specialised approaches"
      - section: "PRIVACY AND OPENNESS"
        contents:
          - href: 5_PRIVACY_OPENNESS/5_1_Introduction.qmd
            text: "PRIVACY AND OPENNESS"
# End Website


# Begin Format
format:
  html:
    theme: 
      - cosmo
      - lmu-osc-custom.scss
    css: 
      - https://raw.githubusercontent.com/lmu-osc/branding-resources/refs/heads/main/lmu-osc-styles.css
    toc: true
    fontsize: 13pt
    code-overflow: wrap
    grid:
      sidebar-width: 300px
    include-in-header:
      - file: matomo-analytics.html
# End Format

# Begin Editor
editor: source
# End Editor
